version: 2.1

orbs:
  win: circleci/windows@1.0.0

references:
  nodejs_versions:
    - &nodejs_current "10"
    - &nodejs_next "12"
    - &nodejs_experimental "14"

  nodejs_enum: &nodejs_enum
    type: enum
    default: *nodejs_current
    enum:
      - *nodejs_current
      - *nodejs_next
      - *nodejs_experimental
  repo_path: &repo_path ~/repo
  defaults: &defaults
    working_directory: *repo_path

workflows:
  node-tests:
    jobs:
      - build:
          name: build-nodejs-current
          nodejs: *nodejs_current
          filters:
            tags:
              only: /.*/
      - build:
          name: build-nodejs-next
          nodejs: *nodejs_next
          filters:
            tags:
              only: /.*/
      - build:
          name: build-nodejs-experimental
          nodejs: *nodejs_experimental
          filters:
            tags:
              only: /.*/
      - test-windows
      - release-tag:
          nodejs: *nodejs_current
          requires:
            - build-nodejs-current
            - build-nodejs-next
            - build-nodejs-experimental
            - test-windows
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

jobs:
  build:
    parameters:
      nodejs:
        <<: *nodejs_enum
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.nodejs >>
    steps:
      - attach_project_repo
      - checkout
      - restore_build_cache:
          suffix: << parameters.nodejs >>
      - run_npm_ci
      - save_build_cache:
          suffix: << parameters.nodejs >>
      - run_npm_build:
          node_env: test
      - run: npm run test
      - when:
          condition:
            equal: [*nodejs_current, << parameters.nodejs >>]
          steps:
            - persist_project_repo

  test-windows:
    <<: *defaults
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - restore_build_cache:
          suffix: windows
      - run_npm_ci
      - save_build_cache:
          suffix: windows
      - run_npm_build:
          node_env: test
      - run: npm run test

  release-tag:
    parameters:
      nodejs:
        <<: *nodejs_enum
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.nodejs >>
    steps:
      - attach_project_repo
      - run_npm_build:
          node_env: production
      - run:
          name: npm registry auth
          command: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
      - run:
          name: npm registry publish
          command: npm publish --access=public

commands:
  attach_project_repo:
    description: attach repo from workspace
    steps:
      - attach_workspace:
          at: *repo_path

  persist_project_repo:
    description: persist repo in workspace
    steps:
      - persist_to_workspace:
          root: *repo_path
          paths: .

  restore_build_cache:
    description: restore npm package cache
    parameters:
      suffix:
        type: string
        default: default
    steps:
      - restore_cache:
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}-<< parameters.suffix >>

  save_build_cache:
    description: save npm package cache
    parameters:
      suffix:
        type: string
        default: default
    steps:
      - save_cache:
          key: npm-packages-{{ checksum "package-lock.json" }}-<< parameters.suffix >>
          paths:
            - ./node_modules

  run_npm_ci:
    description: install npm dependencies
    steps:
      - run: npm ci

  run_npm_build:
    description: build project in << parameters.node_env >> mode
    parameters:
      node_env:
        type: enum
        default: production
        enum: ["production", "test"]
    steps:
      - run:
          command: npm run build --if-present
          environment:
            NODE_ENV: << parameters.node_env >>

  # This is required to avoid a `EACCES` when running `npm link` (which is
  # executed in the test suite).
  configure_global_npm:
    description: create custom directory for global npm installs
    steps:
      - run: |
          mkdir -p ~/.npm-global
          npm config set prefix '~/.npm-global'
